import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeToggle from "@/components/ThemeToggle";
import { Providers } from "./providers";
import NavLinks from "@/components/NavLinks";
import Link from "next/link";
import { auth } from "@/auth";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-white dark:bg-gray-950 transition-colors">
        <header className="w-full p-4 flex justify-between items-center border-b border-gray-200 dark:border-gray-800">
          <Link href="/" className="text-xl font-extrabold text-blue-600 dark:text-blue-400 tracking-tight">
            CareerHub
          </Link>
          <div className="flex items-center gap-6">
            <nav>
              <NavLinks user={session?.user as any} />
            </nav>
            <ThemeToggle />
          </div>
        </header>
        <div className="flex-1 flex flex-col">
          <Providers>
            {children}
          </Providers>
          <Toaster position="bottom-right" richColors />
        </div>
      </body>
    </html>
  );
}
